# version: "3.9"

networks:
  backend:

include:
  - ./infrastructure/postgres/docker-compose.postgres.yml
  - ./infrastructure/kafka/docker-compose.kafka.yml
  - ./infrastructure/redis/docker-compose.redis.yml
  - ./infrastructure/qdrant/docker-compose.qdrant.yml

x-debug-command: &debug-command
  # command: >
  #   python -m debugpy --listen 0.0.0.0:5678
  #   -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  command: >
    python -m uvicorn app.main:app 
    --host 0.0.0.0 --port 8000 --reload

services:
  # auth-service:
  #   build: ./services/auth-service
  #   ports: ["8001:8000", "5678:5678"]
  #   volumes:
  #     - ./services/auth-service:/app
  #     # for https certs (using mkcert localhost for local development)
  #     - ./infrastructure/certs:/certs
  #   env_file:
  #     - .env
  #     - ./services/auth-service/.env
  #   environment:
  #     WATCHFILES_FORCE_POLLING: "true"
  #   command: >
  #     python -m uvicorn app.main:app
  #     --host 0.0.0.0 --port 8000 --reload
  #     --ssl-keyfile /certs/localhost+2-key.pem
  #     --ssl-certfile /certs/localhost+2.pem
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy

  #   networks: [backend]

  user-service:
    build: ./services/user-service
    ports: ["8002:8000", "5679:5678"]
    volumes:
      - ./services/user-service:/app
      - ./infrastructure/certs:/certs
    env_file:
      - .env
      - ./services/user-service/.env
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    command: >
      python -m uvicorn app.main:app 
      --host 0.0.0.0 --port 8000 --reload
      --ssl-keyfile /certs/localhost+2-key.pem 
      --ssl-certfile /certs/localhost+2.pem
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

    networks: [backend]

  rag-service:
    build: ./services/rag-service
    ports: ["8003:8000", "5680:5678"]
    volumes:
      - ./services/rag-service:/app
      - ./infrastructure/certs:/certs
    env_file:
      - .env
      - ./services/rag-service/.env
    environment:
      QDRANT_ADDR: qdrant:6334
      WATCHFILES_FORCE_POLLING: "true"
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
      --ssl-keyfile /certs/localhost+2-key.pem 
      --ssl-certfile /certs/localhost+2.pem
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    networks: [backend]

  ingest-service:
    build: ./services/ingest-service
    ports: ["8004:8000", "5681:5678"]
    volumes:
      - ./services/ingest-service:/app
      - ./infrastructure/certs:/certs
    env_file:
      - .env
      - ./services/ingest-service/.env
    environment:
      QDRANT_ADDR: qdrant:6334
      WATCHFILES_FORCE_POLLING: "true"
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
      --ssl-keyfile /certs/localhost+2-key.pem 
      --ssl-certfile /certs/localhost+2.pem
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    networks: [backend]

  document-processor-service:
    build: ./services/document-processor-service
    ports: ["8005:8000", "5682:5678"]
    volumes:
      - ./services/document-processor-service:/app
      - ./infrastructure/certs:/certs
    env_file:
      - .env
      - ./services/document-processor-service/.env
    environment:
      QDRANT_ADDR: qdrant:6334
      WATCHFILES_FORCE_POLLING: "true"
    command: >
      python -m uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
      --ssl-keyfile /certs/localhost+2-key.pem 
      --ssl-certfile /certs/localhost+2.pem
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

    networks: [backend]

  # notification-service:
  #   build: ./services/notification-service
  #   ports: ["8006:8000", "5683:5678"]
  #   volumes:
  #     - ./services/notification-service:/app
  #     - ./infrastructure/certs:/certs
  #   env_file:
  #     - .env
  #     - ./services/notification-service/.env
  #   environment:
  #     WATCHFILES_FORCE_POLLING: "true"
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy

  #   networks: [backend]

  # audit-service:
  #   build: ./services/audit-service
  #   ports: ["8007:8000", "5684:5678"]
  #   volumes:
  #     - ./services/audit-service:/app
  #     - ./infrastructure/certs:/certs
  #   env_file:
  #     - .env
  #     - ./services/audit-service/.env
  #   environment:
  #     WATCHFILES_FORCE_POLLING: "true"
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy

  #   networks: [backend]

  # api-gateway:
  #   build: ./services/api-gateway
  #   ports: ["8000:8000"]
  #   volumes:
  #     - ./services/api-gateway:/app
  #     - ./infrastructure/certs:/certs
  #   env_file:
  #     - .env
  #     - ./services/api-gateway/.env
  #   environment:
  #     WATCHFILES_FORCE_POLLING: "true"
  #   depends_on: [auth-service, user-service, rag-service, ingest-service]
  #   networks: [backend]
