"""make chat email non unique

Revision ID: 19ae0f1e7706
Revises: aa3f7c84adcc
Create Date: 2026-07-26 17:52:18.002712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ae0f1e7706'
down_revision: Union[str, Sequence[str], None] = 'aa3f7c84adcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_email'), table_name='chats')
    op.create_index(op.f('ix_chats_email'), 'chats', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_email'), table_name='chats')
    op.create_index(op.f('ix_chats_email'), 'chats', ['email'], unique=True)
    # ### end Alembic commands ###
