"""add: optional file mime type

Revision ID: 55dc2d463e79
Revises: a775f46bac67
Create Date: 2026-07-22 19:14:53.009887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dc2d463e79'
down_revision: Union[str, Sequence[str], None] = 'a775f46bac67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_mime_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_mime_type')
    # ### end Alembic commands ###
