"""create documents table

Revision ID: a775f46bac67
Revises: 
Create Date: 2026-07-03 13:45:55.340524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a775f46bac67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('library_name', sa.String(length=255), nullable=True),
    sa.Column('library_id', sa.String(length=255), nullable=True),
    sa.Column('site_url', sa.Text(), nullable=False),
    sa.Column('parent_folder_path', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('ingest_initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_status', sa.String(length=50), server_default='started', nullable=False),
    sa.Column('prev_batch_ingest_init', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_by_id'), 'documents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_documents_file_url'), 'documents', ['file_url'], unique=True)
    op.create_index(op.f('ix_documents_library_id'), 'documents', ['library_id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_library_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_url'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
