general_skip_list = [
    "hi",
    "hello",
    "hey",
    "yo",
    "good morning",
    "good afternoon",
    "good evening",
    "howdy",
    "hiya",
    "sup",
    "what's up",
    "bye",
    "goodbye",
    "thanks",
    "thank you",
    "ok",
    "okay",
    "yes",
    "no",
    "sure",
    "cool",
    "awesome",
    "great",
    "how are you",
    "help",
    "yeah",
    "yep",
    "nope",
    "hmm",
    "um",
    "see you",
    "later",
    "take care",
    "farewell",
    "thx",
    "ty",
    "kk",
    "got it",
    "understood",
    "roger",
    "sounds good",
    "perfect",
    "nice",
    "yup",
    "certainly",
    "absolutely",
    "indeed",
    "correct",
    "right",
    "hmmm",
    "uh",
    "uhh",
    "huh",
    "...",
    "hello there",
    "how's it going",
    "what's new",
    "good job",
    "nice work",
    "well done",
    "",
    " ",
    "\n",
    "??",
    "!",
    ".",
]

# _stop_words = [
#     "hi",
#     "hello",
#     "hey",
#     "yo",
#     "good morning",
#     "good afternoon",
#     "good evening",
#     "howdy",
#     "hiya",
#     "sup",
#     "what's up",
#     # ---------------------------
#     "hi",
#     "hello",
#     "hey",
#     "good morning",
#     "good afternoon",
#     "good evening",
#     "bye",
#     "goodbye",
#     "thanks",
#     "thank you",
#     "ok",
#     "okay",
#     "yes",
#     "no",
#     "sure",
#     "cool",
#     "awesome",
#     "great",
#     "how are you",
#     "what's up",
#     "help",
#     "hi",
#     "hello",
#     "hey",
#     "good morning",
#     "good afternoon",
#     "good evening",
#     "bye",
#     "goodbye",
#     "thanks",
#     "thank you",
#     "ok",
#     "okay",
#     "cool",
#     "great",
#     "awesome",
#     "yes",
#     "yeah",
#     "yep",
#     "sure",
#     "no",
#     "nope",
#     "how are you",
#     "what's up",
#     "help",
#     "hmm",
#     "um",
#     # ---------------------------
#     "bye",
#     "goodbye",
#     "see you",
#     "later",
#     "take care",
#     "farewell",
#     # ---------------------------
#     "bye",
#     "goodbye",
#     "see you",
#     "later",
#     "take care",
#     "farewell",
#     # ---------------------------
#     "thanks",
#     "thank you",
#     "thx",
#     "ty",
#     "ok",
#     "okay",
#     "kk",
#     "cool",
#     "got it",
#     "understood",
#     "roger",
#     "sounds good",
#     "great",
#     "awesome",
#     "perfect",
#     "nice",
#     # ---------------------------
#     "yes",
#     "yep",
#     "yeah",
#     "yup",
#     "sure",
#     "certainly",
#     "absolutely",
#     "indeed",
#     "correct",
#     "right",
#     # ---------------------------
#     "hmm",
#     "hmmm",
#     "uh",
#     "uhh",
#     "um",
#     "huh",
#     "...",
#     # ---------------------------
#     "help",
#     "hello there",
#     "how are you",
#     "how's it going",
#     "what's new",
#     "good job",
#     "nice work",
#     "well done",
#     # ---------------------------
#     "",
#     " ",
#     "\n",
#     "...",
#     "??",
#     "!",
#     ".",
#     # ---------------------------
# ]
